steps:
- name: 'bash'
  id: 'Create Cache Buster File'
  args: ['-c', 'echo "$BUILD_ID" > build_id.txt']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Image'
  args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/xavibot-personal/xavibot/app-image:latest'
    - '.'
  waitFor: ['Create Cache Buster File']

images:
- 'us-central1-docker.pkg.dev/xavibot-personal/xavibot/app-image:latest'
